variables:
    IMAGE: centos/centos7-helm3:0.01

stages:
  - build
  
stage: build

  before_script:
    - export HELM_EXPERIMENTAL_OCI=1
    - helm registry login $REGISTRY/$PROJECT -u $HARBOR_USERNAME -p $HARBOR_PASSWORD
    - git config --global user.email "$GIT_USERNAME@github.com"
    - git config --global user.user "$GIT_USERNAME"
  script:
    - git checkout master
    - helm dependecy update ./
    - git add --all
    - git commit -m "update dependecy"
    - git push "http://$GIT_USERNAME:$GIT_PASSWORD@$GIT_FQDN/$CI_PROJECT_PATH.git"
  only:
    refs:
      - master
    changes:
      - Chart.yaml
